pid /tmp/nginx-music-orderer-ui.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    types_hash_max_size 4096;

    access_log /tmp/nginx-music-orderer-ui/access.log;
    error_log  /tmp/nginx-music-orderer-ui/error.log;

    client_body_temp_path /tmp/nginx-music-orderer-ui/client-body;
    proxy_temp_path       /tmp/nginx-music-orderer-ui/proxy;
    fastcgi_temp_path     /tmp/nginx-music-orderer-ui/fastcgi;
    uwsgi_temp_path       /tmp/nginx-music-orderer-ui/uwsgi;
    scgi_temp_path        /tmp/nginx-music-orderer-ui/scgi;

    server {
        listen 8080;
        server_name dev.bardomusic.uk localhost;

        root dist;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://localhost:3001;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
